version: '3'
services:
  app:
    image: php:7.3.4-fpm
    tty: true
    restart: unless-stopped
    expose:
      - 9000
    depends_on:
      - db
      - nginx
    volumes:
      - ./app/:/app/
    command: "php-fpm"
    working_dir: /app/
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "9380:80"
    volumes:
      - ./app/:/app/
      - ./.docker/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  pg:
    image: postgres:11.2-alpine
    environment:
      - LC_COLLATE=ru_RU.UTF-8
      - LC_CTYPE=ru_RU.UTF-8
      - POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS="--locale=ru_RU"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql
    networks:
      - app-network

  db:
    image: brainsam/pgbouncer:1.8.1
    restart: unless-stopped
    environment:
      - DB_HOST=pg
      - AUTH_TYPE=trust
      - AUTH_FILE=/auth_file.txt
      - POOL_MODE=transaction
      - LISTEN_PORT=5432
      - SERVER_LOGIN_RETRY=1
    volumes:
      - ./.docker/configs/auth_file.txt:/auth_file.txt
    depends_on:
      - pg
    ports:
      - "9325:5432"
    expose:
      - "5432"
    networks:
      - app-network

volumes:
  app:
  data:

networks:
  app-network:
    driver: bridge